import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ReduxProvider from "@/app/redux/provider/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="container mx-auto max-w-[1400px] justify-center">
            <div className="fixed top-0 z-50 w-full">
              <Navbar />
            </div>

            {children}
          </div>
        </body>
      </html>
    </ReduxProvider>
  );
}
